services:
  - type: web
    name: pixelcleaner
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 600 --workers 2 --threads 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

